---

- hosts: nodes
  become: yes
  tasks:

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Enable nginx
      service:
        name: nginx
        enabled: yes
    - name: Creating a file with content
      copy:
        dest: /home/ubuntu/index.html
        content: |
          This was created using ansible

    - name: this will replace the index.html file
      copy:
        src: /home/ubuntu/index.html
        dest: /var/www/html/index.html
        remote_src: yes
